# global:
#   scrape_interval: 35s # DENNA SKA VARA MINST 30 SEN

# scrape_configs:
#   - job_name: "node"
#     static_configs:
#       - targets: ["node-exporter:9100"]
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["0.0.0:9090"]

global:
  scrape_interval: 35s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 35s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    scrape_interval: 35s
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "flaskapp"
    static_configs:
      - targets: ["{{ groups['appServer'][0] }}:8000"]
