version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: mathilda17/microblog
    docker:
      - image: cimg/base:2021.04
jobs:
  build:
    # working_directory: ~/repo
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install python3-pip
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install pylint
            sudo pip install ansible
            make install-test
            make install-deploy
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -f docker/Dockerfile_prod.dockerfile -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u mathilda17 --password-stdin
            docker push $IMAGE_NAME:latest
  ansible:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install python3-pip
            sudo apt-get install python3-venv
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install pylint
            sudo pip install ansible
            make install-test
            make install-deploy
      - run:
          name: run ansible script
          command: ansible-playbook ansible/gather_vm_instances.yml ansible/appServer.yml
  snyk:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV # här gör vi så att så att CircleCi automatisk laddar venv och då kollar Snyk vad vi har installerat i den.
      - snyk/scan
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - ansible:
          requires:
            - publish-latest
          filters:
            branches:
              only: master
      - snyk:
          filters:
            branches:
              only: master
