version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install pylint
            make install-test
            sudo apt-get install python3-venv
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t mathilda17/microblog:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
