---
serviceName: "prometheus"
userId: "prometheus"
groupId: "prometheus"
command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"
version: "2.3.2"
