- name: Install nessesary package
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Copy grafana config file
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini

- name: Start grafana server
  service:
    name: grafana-server
    enabled: true
    state: started
