- name: Update the apt package
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ packagesdep }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - python3-pip
      - virtualenv
      - python3-setuptools

- name: Add Apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Debian Stretch, official repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Add new repo to cache
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install docker
  apt:
    name: "docker-ce"
    state: latest

- name: Install Docker for Python
  pip:
    name: docker
